1. What is a Python library? Why do we use Python libraries?

2. What is the difference between Numpy array and List?

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

shape = arr.shape
size = arr.size
dimension = arr.ndim

print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimension of the array:", dimension)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

first_row = arr[0]

print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = arr[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2].flatten()

print("Odd-indexed elements from the array:", odd_indexed_elements)


Odd-indexed elements from the array: [ 2  4  6  8 10 12]


7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [5]:
import numpy as np

random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.22544237 0.82102569 0.69445788]
 [0.78521505 0.86485776 0.43840823]
 [0.65422134 0.74349899 0.85768797]]


8. Describe the difference between np.random.rand and np.random.randn?

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

expanded_arr = np.expand_dims(arr, axis=2)

print("Original array:")
print(arr)
print("\nExpanded array with an additional dimension:")
print(expanded_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded array with an additional dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_arr = np.transpose(arr)

print("Original array:")
print(arr)
print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
a. Index wise multiplication
b. Matix multiplication
c. Add both the maticK
d. Subtact matix B from A 
e. Divide Matix B by A

In [8]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A2 * B2

# Matrix multiplication
matrix_multiplication = np.matmul(A2, B2.T)  # Transpose of B2 is taken to match dimensions

# Matrix addition
matrix_addition = A2 + B2

# Matrix subtraction
matrix_subtraction = A2 - B2

# Division of matrix B2 by A2
division_matrix = np.divide(B2, A2)

# Print results
print("Index-wise multiplication:")
print(index_wise_multiplication)

print("\nMatrix multiplication:")
print(matrix_multiplication)

print("\nMatrix addition:")
print(matrix_addition)

print("\nMatrix subtraction:")
print(matrix_subtraction)

print("\nDivision of matrix B2 by A2:")
print(division_matrix)


Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of matrix B2 by A2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be use^ to swap the byte or^er of an array?

13. What is the significance of the np.linalg.inv function?

14. What does the np.reshape function do, and how is it used?

15. What is broadcasting in Numpy?